-- MySQL Script generated by MySQL Workbench
-- 03/03/17 11:43:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contacto` (
  `contacto_id` INT NOT NULL AUTO_INCREMENT,
  `cont_nombre` VARCHAR(100) NULL,
  `cont_correo_electronico` VARCHAR(80) NULL,
  `cont_calle` VARCHAR(60) NULL,
  `cont_colonia` VARCHAR(60) NULL,
  `cont_num_ext` VARCHAR(45) NULL,
  `cont_num_int` VARCHAR(45) NULL,
  `cont_delegacion` VARCHAR(45) NULL,
  `cont_entidad_federativa` VARCHAR(45) NULL,
  `cont_pais` VARCHAR(70) NULL,
  `cont_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`contacto_id`))
ENGINE = InnoDB
COMMENT = '																																								';


-- -----------------------------------------------------
-- Table `telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telefono` (
  `telefono_id` INT NOT NULL AUTO_INCREMENT,
  `tel_numero` VARCHAR(45) NULL,
  `contacto_id` INT NOT NULL,
  PRIMARY KEY (`telefono_id`),
  CONSTRAINT `fk_telefono_contacto`
    FOREIGN KEY (`contacto_id`)
    REFERENCES `contacto` (`contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefono_contacto_idx` ON `telefono` (`contacto_id` ASC);


-- -----------------------------------------------------
-- procedure getContactos
-- -----------------------------------------------------

DELIMITER $$
CREATE PROCEDURE `getContactos` ()
BEGIN
	SELECT contacto.*, telefono.tel_numero FROM contacto 
    LEFT JOIN telefono ON (contacto.contacto_id = telefono.telefono_id)
    ;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
