<?php echo $this->headScript()->prependFile($this->baseUrl() . '/js/agenda.js');?>
<script>
    $(document).ready(function(){
        loadList();
    });
</script>
<div class="row">
    <div class="col-xs-12 text-right">
        <button class="btn btn-success btn-md" onclick="editContacto();">
            <i class="glyphicon glyphicon-plus"></i><i class="glyphicon glyphicon-user"></i> 
        </button>
    </div>
</div>
<div class="modal fade" id="mdEditar" tabindex="-1" role="dialog" aria-labelledby="mdEditarLabel" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-center" id="mdEditarLabel"></h4>
            </div>
            <div class="modal-body">
                
            </div>
        </div>
    </div>
</div>    
<div id="list-contactos">
    
</div>