<?php 
if (empty($this->contactos)) { ?>
<div class="alert alert-warning text-center" role="alert">Aún no existen contactos registrados.</div>
<?php
} else {?>
<table class="table table-striped table-hover">
    <?php
    foreach ($this->contactos as $contacto) { ?>
        <tr>
            <td>
                <div class="row">
                    <div class="col-xs-2 col-sm-1 text-center">
                        <button type="button" class="btn btn-primary" onclick="editContacto(<?php echo htmlentities($contacto->id);?>);"><i class="glyphicon glyphicon-pencil"></i></button>
                    </div>
                    <div class="col-xs-7 col-sm-9">
                        <h4><i class="glyphicon glyphicon-user"></i> <?php echo htmlentities($contacto->nombre);?></h4>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i> <?php echo htmlentities($contacto->correoElectronico);?><br />
                            <i class="glyphicon glyphicon-home"></i> 
                            <?php echo (empty((array)$contacto->calle) ? '' : 'Calle ' . htmlentities($contacto->calle) . ', ');?>
                            <?php echo (empty((array)$contacto->numExt) ? '' : 'No. ext. ' . htmlentities($contacto->numExt) . ', ');?>
                            <?php echo (empty((array)$contacto->numInt) ? '' : 'No. int. ' . htmlentities($contacto->numInt) . ', ');?>
                            <?php echo (empty((array)$contacto->colonia) ? '' : 'Col. ' . htmlentities($contacto->colonia) . ', ');?>
                            <?php echo (empty((array)$contacto->delegacion) ? '' : 'Del. ' . htmlentities($contacto->delegacion) . ', ');?>
                            <?php echo (empty((array)$contacto->pais) ? '' : htmlentities($contacto->pais));?>.
                        </p>
                    </div>
                    <div class="col-xs-2">
                        <span class="text-success">(<?php echo $contacto->timestamp;?>)</span>
                    </div>
                </div>
            </td>
        </tr>
    <?php 
    }?>
</table>
<?php
}