<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle((isset($this->headTitle) ? $this->headTitle : '')); ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-3.1.1.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrapValidator.min.js')
                ->appendFile($this->baseUrl() . '/js/notify.min.js')
                ->appendFile($this->baseUrl() . '/js/general.js'); ?>
        
        <?php echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . '/css/sticky-footer-navbar.css')
                ->appendStylesheet($this->baseUrl() . '/css/custom.css'); ?>
        <link href="https://fonts.googleapis.com/css?family=Ubuntu+Condensed" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
        <script>
            var baseUrl = '<?php echo $this->baseUrl();?>';
            var ERROR_OK = 0;
            var ERROR_FAIL = 1;
        </script>
    </head>
    <body>
        <?php echo $this->render('header.phtml'); ?>

        <div class="container ">
            <?php echo $this->layout()->content; ?>
        </div>

        <?php echo $this->render('footer.phtml') ?>
    </body>
</html>
